### ISSUE TITLE
How to set batch size when training AllSet?

### ISSUE THREAD

**Issue by thu-wangz17** [jianhao2016/AllSet#2]
Hi, this is a nice work. I read the code:
https://github.com/jianhao2016/AllSet/blob/0d0e399a9168829fa898dd56f3d32bee36953b04/src/train.py#L325-L327
https://github.com/jianhao2016/AllSet/blob/0d0e399a9168829fa898dd56f3d32bee36953b04/src/train.py#L345
https://github.com/jianhao2016/AllSet/blob/0d0e399a9168829fa898dd56f3d32bee36953b04/src/train.py#L478
It seems that you train the model with all the data in a batch. Thus I have a question about how to set batch size when I train the `AllSet` model. Thank you.

**Comment by elichienxD** [comment]
Hi @sakuraiiiii ,

This is a great question! Unfortunately, mini-batch training in AllSet is currently an open problem, where we stated in our paper (Appendix A). We conjecture one can develop a GraphSAINT or ClusterGCN type of method to allow mini-batch training. There are also many open directions stated in Appendix A, which we conjecture that one can leverage the similar idea in the GNN literature.

Please let me know if you manage to develop mini-batch training! It would be a great improvement to AllSet and to general hypergraph neural networks!

Best,
Eli

**Comment by thu-wangz17** [comment]
Thank you very much. If I fix this question, I will give you feedback :)
