### ISSUE TITLE
Feature dimension of Walmart and house dataset

### ISSUE THREAD

**Issue by wangfuli** [jianhao2016/AllSet#4]
Hi AllSet authors,

In the appendix of the paper, I noticed that the feature dimensions of the House and Walmart dataset are fixed to 100, but I found that in the code, the feature dimensions are in [num_nodes, num_classes] of the "load_other_datasets.py" file.

<img width="740" alt="image" src="https://user-images.githubusercontent.com/48502117/172494992-235cc174-a20d-4906-b1e7-9784428c2852.png">

I guess it is just a typo but still would like to double-check with you which dimension (100, or num_classes) was used for the reported results in the paper. 

Thank you for making the three new datasets available to the community, the paper is really a solid work!

**Comment by elichienxD** [comment]
Hi @wangfuli ,

Thanks for your kind words, I'm glad that you find our work useful!

Regarding your question, note that we have `feature_dim` as an input argument. So, when `feature_dim` is given and it is greater than `num_classes`, then an additional "noisy feature dimension" is appended. See Line 322 to 324. More specifically, see Line 324 in your screenshot that we do stack addition dimensions to the features. 

That being said, we do set the feature dimension to 100 for House and Walmart in our experiment. Please let me know if you have any further questions!

Best,
Eli

**Comment by wangfuli** [comment]
Thank you so much for your prompt reply, Eli. I got the idea now. :)
