### ISSUE TITLE
Dimension size issue

### ISSUE THREAD

**Issue by levtelyatnikov** [jianhao2016/AllSet#5]
when running HCHA experiment getting next error:    
```
 self.__set_size__(size, dim, data)
  File "/opt/anaconda3/envs/wave-pyg/lib/python3.9/site-packages/torch_geometric/nn/conv/message_passing.py", line 165, in __set_size__
    raise ValueError(
ValueError: Encountered tensor with size 4287 in dimension 0, but expected size 2708.
```

**Comment by elichienxD** [comment]
Hi @levtelyatnikov ,

Did you use the exact version of PyG as ours?

If so, may I ask which data did you use and the full comment (i.e., ``./run_one_model.sh cora HCHA 64 64 1``) to reproduce your bug?

I just check it on my server again and it does not have the bug you mentioned. 
![image](https://user-images.githubusercontent.com/46387845/208039200-bc4aa1c0-aa02-4869-9a69-ab82f14412eb.png)

Best,
Eli

**Comment by elichienxD** [comment]
Hi @levtelyatnikov ,

You may also want to check #1 if you are using the latest PyG version. We provide the way to modify our code therein.

Best,
Eli

**Comment by levtelyatnikov** [comment]
yes, that is exactly the issue which I was facing, thank you, great work!

**Comment by elichienxD** [comment]
Hi @levtelyatnikov ,

Glad that your issue is resolved! I'll close the issue but feel free to open another one if you have any problems.

Best,
Eli
