### ISSUE TITLE
weighted hypergraph 

### ISSUE THREAD

**Issue by JMian** [jianhao2016/AllSet#6]
Model: AllSetTransformer 
If I understood correctly, in the original code implementation all the hyperedges are assumed to have unit weight. Now my hypergraph has weighted hyperedges, how do I integrate this information into the code?  

I noticed the comment below https://github.com/jianhao2016/AllSet/blob/15cbc85a9c325815ab7b8f4bf51ff8e56bac2628/src/models.py#L330 . If the hyperedge weight can be considered as hyperedge feature, where do I concat the hyperedge weight exactly? Is it after the final output of the PMA of the self.V2EConvs block i.e. https://github.com/jianhao2016/AllSet/blob/15cbc85a9c325815ab7b8f4bf51ff8e56bac2628/src/layers.py#L157 ?

**Comment by elichienxD** [comment]
Hi @JMian ,

Thanks for being interested in our work! I believe your understanding is correct. Just concatenate your edge feature with the output of self.V2EConvs blocks. Remember to change the E_in_dim accordingly. Please let us know if it works well or if you encounter other issues with this approach. I am also interested in knowing how AllSet would work on your data :)

Best,
Eli

**Comment by JMian** [comment]
Thanks for confirming. I have concatenated the hyperedge weights with the output of self.V2EConvs block and it worked. I’ve also tried the another approach by multiplying the output of self.V2EConvs block by the hyperedge weight, it seems to work too. However, as of now I can’t say for sure which approach is better, probably needs more training and/or hypeparameter tuning to tell.  As I am using AllSet with the other downstream task, I didn’t separate out AllSet from the overall task to test its performance on my data. Nevertheless, the metrics for the overall task is definitely improving. Thanks!
