### ISSUE TITLE
Model performance

### ISSUE THREAD

**Issue by levtelyatnikov** [jianhao2016/AllSet#7]
Hi, I am running models to see the results and experiments with parameters and sometimes I obtain the results which are completely different from the ones which are depicted in the paper. 
For example next setting: ["--method", "CEGCN", "--dname", "cora", "--All_num_layers", "5", "--MLP_num_layers", "999", "--Classifier_num_layers", "999", "--MLP_hidden", "256",  "--Classifier_hidden", "256", "--wd", "0.0", "--epochs", "100", "--feature_noise", "0.0", "--runs", "20" ,"--cuda", "0", "--lr", "0.001"]

gives me Highest 
Train: 97.64 ± 1.31
Highest Valid: 92.18 ± 5.39
Final Train: 93.92 ± 1.91
Final Test: 92.22 ± 5.24

While in the table CEGCN gives: 76.17 ± 1.39

Can I ask for a comment on this issue?

**Comment by elichienxD** [comment]
Hi @levtelyatnikov ,

Thank you for being interested in our work! I have re-run the experiment on cora with the commend
```
python train.py --method CEGCN --dname cora --All_num_layers 5 --MLP_hidden 256 --Classifier_hidden 256 --wd 0.0 --epochs 100 --feature_noise 0.0 --runs 10 --cuda 0 --lr 0.001
```
However I can only get the following result
![image](https://user-images.githubusercontent.com/46387845/214764673-c329cfb1-6931-4ba4-a681-0122ed36c824.png)

Could you share the exact command you execute (like the one I show above) and also the version of PyG you are using?

Best,
Eli

**Comment by levtelyatnikov** [comment]
Hi, my version of PyG is 2.0.4
I executed the same command and obtaining next results 
<img width="579" alt="image" src="https://user-images.githubusercontent.com/23523959/215014715-73d7510e-f060-4720-97b0-23da11913dd4.png">

**Comment by elichienxD** [comment]
Hi @levtelyatnikov ,

Could you try with the exact same PyG version we used (torch-geometric==1.6.3)? It may be some PyG version issue. Please check the Readme file for the environment setup details. Note that PyG has changed its data format after 2.0 (or some newer version) so things might be messed up. If you still run into issues with PyG 1.6.3 version, please let me know.

On the other hand, it seems like other people have no issue with running CEGCN (see for example issue #1). Maybe you also want to check it to see how PyG version difference can cause issue.

Best,
Eli

**Comment by elichienxD** [comment]
Hi @levtelyatnikov ,

Since there's no more follow-up, I close the issue for now. Please feel free to reopen the issue if you have further questions.

Best,
Eli
