### ISSUE TITLE
New datasets

### ISSUE THREAD

**Issue by levtelyatnikov** [jianhao2016/AllSet#8]
Hi, I want to extend the possible datasets which I can utilise, however as I can see there is not code in the repository to generate the hyperedges from simple graph. Can I ask you to provide the code? 
Thank you

**Comment by levtelyatnikov** [comment]
I examined the "cora" dataset closely and found that some nodes do not participate in any hyperedge (around 47% of nodes do not participate). The paper states that the hyperedges are constructed from initial pairwise interactions. I verified that every node in the original edges of the "cora" dataset has a neighbor. Can you explain what I am misunderstanding?

**Comment by elichienxD** [comment]
Hi @levtelyatnikov ,

Thanks for the question. Regarding the cora dataset, we directly obtained from Yadati et al. (2019), the HyperGCN paper, as we stated in our paper (page 8). Thus we did not generate this dataset nor include codes for generating hyperedges from a simple graph. Could you let me know where you see the claim on generating cora from simple edges in our paper?

Regarding how Yadati et al. (2019) generate their datasets, please check section 12 in their [paper](https://arxiv.org/pdf/1809.02589.pdf). I do not think they generate hypergraphs from simple graphs either.

Finally, to include your own datasets, please check how we store the data. For example, see [here](https://github.com/jianhao2016/AllSet/blob/15cbc85a9c325815ab7b8f4bf51ff8e56bac2628/src/load_other_datasets.py#L121) in our code.

Best,
Eli

**Comment by elichienxD** [comment]
Hi @levtelyatnikov ,

Since there's no more follow-up, I close the issue for now. Please feel free to reopen the issue if you have further questions.

Best,
Eli
